In [1]:
import pandas as pd
import numpy as np

In [3]:
salary_train = pd.read_csv(r"D:\Naive_Bayes_salary_Train_test_data\SalaryData_Train.csv")

salary_test =pd.read_csv(r"D:\Naive_Bayes_salary_Train_test_data\SalaryData_Test.csv")

In [4]:
salary_train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [5]:
salary_test.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K

In [6]:
salary_train.shape

(30161, 14)

In [7]:
salary_test.shape

(15060, 14)

In [8]:
salary_test.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [9]:
salary_train.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [10]:
salary_train1=salary_train.drop('educationno',axis=1)

In [11]:
salary_train1.columns

Index(['age', 'workclass', 'education', 'maritalstatus', 'occupation',
       'relationship', 'race', 'sex', 'capitalgain', 'capitalloss',
       'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [12]:
str_col=['workclass','education','maritalstatus','occupation','relationship','race','sex','native']

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
labelencoder = LabelEncoder()

In [15]:
for i in str_col:
    salary_train1[i]=labelencoder.fit_transform(salary_train1[i])

In [16]:
salary_train1.head(20)

,age,workclass,education,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,5,9,4,0,1,4,1,2174,0,40,37,<=50K
1,50,4,9,2,3,0,4,1,0,0,13,37,<=50K
2,38,2,11,0,5,1,4,1,0,0,40,37,<=50K
3,53,2,1,2,5,0,2,1,0,0,40,37,<=50K
4,28,2,9,2,9,5,2,0,0,0,40,4,<=50K
5,37,2,12,2,3,5,4,0,0,0,40,37,<=50K
6,49,2,6,3,7,1,2,0,0,0,16,21,<=50K
7,52,4,11,2,3,0,4,1,0,0,45,37,>50K
8,31,2,12,4,9,1,4,0,14084,0,50,37,>50K
9,42,2,9,2,3,0,4,1,5178,0,40,37,>50K
10,37,2,15,2,3,0,2,1,0,0,80,37,>50K
11,30,5,9,2,9,0,1,1,0,0,40,17,>50K
12,23,2,9,4,0,3,4,0,0,0,30,37,<=50K
13,32,2,7,4,11,1,2,1,0,0,50,37,<=50K
14,34,2,5,2,13,0,0,1,0,0,45,24,<=50K
15,25,4,11,4,4,3,4,1,0,0,35,37,<=50K
16,32,2,11,4,6,4,4,1,0,0,40,37,<=50K
17,38,2,1,2,11,0,4,1,0,0,50,37,<=50K
18,43,4,12,0,3,4,4,0,0,0,45,37,>50K
19,40,2,10,2,9,0,4,1,0,0,60,37,>50K

In [17]:
salary_test.columns

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [18]:
salary_test1=salary_test.drop('educationno',axis=1)

In [19]:
salary_test1.columns

Index(['age', 'workclass', 'education', 'maritalstatus', 'occupation',
       'relationship', 'race', 'sex', 'capitalgain', 'capitalloss',
       'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [20]:
str_col1=['workclass','education','maritalstatus','occupation','relationship','race','sex','native']

In [21]:
for i in str_col1:
    salary_test1[i]=labelencoder.fit_transform(salary_test1[i])

In [22]:
salary_train1.shape

(30161, 13)

In [23]:
salary_test1.shape

(15060, 13)

In [24]:
salary_train1.isnull().sum()

age              0
workclass        0
education        0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [25]:
salary_train1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            30161 non-null  int64
 1   workclass      30161 non-null  int32
 2   education      30161 non-null  int32
 3   maritalstatus  30161 non-null  int32
 4   occupation     30161 non-null  int32
 5   relationship   30161 non-null  int32
 6   race           30161 non-null  int32
 7   sex            30161 non-null  int32
 8   capitalgain    30161 non-null  int64
 9   capitalloss    30161 non-null  int64
 10  hoursperweek   30161 non-null  int64
 11  native         30161 non-null  int32
 12  Salary         30161 non-null  object
dtypes: int32(8), int64(4), object(1)
memory usage: 2.1+ MB

In [26]:
salary_test1.isnull().sum()

age              0
workclass        0
education        0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [27]:
salary_test1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   age            15060 non-null  int64
 1   workclass      15060 non-null  int32
 2   education      15060 non-null  int32
 3   maritalstatus  15060 non-null  int32
 4   occupation     15060 non-null  int32
 5   relationship   15060 non-null  int32
 6   race           15060 non-null  int32
 7   sex            15060 non-null  int32
 8   capitalgain    15060 non-null  int64
 9   capitalloss    15060 non-null  int64
 10  hoursperweek   15060 non-null  int64
 11  native         15060 non-null  int32
 12  Salary         15060 non-null  object
dtypes: int32(8), int64(4), object(1)
memory usage: 1.0+ MB

In [28]:
Xtrain = salary_train1.iloc[: ,0:12]

In [29]:
Xtrain

,age,workclass,education,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native
0,39,5,9,4,0,1,4,1,2174,0,40,37
1,50,4,9,2,3,0,4,1,0,0,13,37
2,38,2,11,0,5,1,4,1,0,0,40,37
3,53,2,1,2,5,0,2,1,0,0,40,37
4,28,2,9,2,9,5,2,0,0,0,40,4
...,...,...,...,...,...,...,...,...,...,...,...,...
30156,27,2,7,2,12,5,4,0,0,0,38,37
30157,40,2,11,2,6,0,4,1,0,0,40,37
30158,58,2,11,6,0,4,4,0,0,0,40,37
30159,22,2,11,4,0,3,4,1,0,0,20,37
30160,52,3,11,2,3,5,4,0,15024,0,40,37

In [30]:
Ytrain = salary_train1.iloc[: , 12]

In [31]:
Ytrain

0         <=50K
1         <=50K
2         <=50K
3         <=50K
4         <=50K
          ...
30156     <=50K
30157      >50K
30158     <=50K
30159     <=50K
30160      >50K
Name: Salary, Length: 30161, dtype: object

In [32]:
Xtest = salary_test1.iloc[ : ,0:12]

In [33]:
Xtest

,age,workclass,education,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native
0,25,2,1,4,6,3,2,1,0,0,40,37
1,38,2,11,2,4,0,4,1,0,0,50,37
2,28,1,7,2,10,0,4,1,0,0,40,37
3,44,2,15,2,6,0,2,1,7688,0,40,37
4,34,2,0,4,7,1,4,1,0,0,30,37
...,...,...,...,...,...,...,...,...,...,...,...,...
15055,33,2,9,4,9,3,4,1,0,0,40,37
15056,39,2,9,0,9,1,4,0,0,0,36,37
15057,38,2,9,2,9,0,4,1,0,0,50,37
15058,44,2,9,0,0,3,1,1,5455,0,40,37
15059,35,3,9,2,3,0,4,1,0,0,60,37

In [34]:
Ytest = salary_test1.iloc[ : ,12]

In [35]:
Ytest

0         <=50K
1         <=50K
2          >50K
3          >50K
4         <=50K
          ...
15055     <=50K
15056     <=50K
15057     <=50K
15058     <=50K
15059      >50K
Name: Salary, Length: 15060, dtype: object

In [36]:
from sklearn.naive_bayes import MultinomialNB as MB
from sklearn.naive_bayes import GaussianNB as GB

In [37]:
salary_MB = MB()

In [38]:
salary_MB.fit(Xtrain,Ytrain)

MultinomialNB()

In [39]:
y_pred = salary_MB.predict(Xtest)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [41]:
acc = accuracy_score(Ytest, y_pred) * 100
print("Accuracy =", acc)

Accuracy = 77.49667994687915

In [42]:
confusion_matrix(Ytest, y_pred)

array([[10891,   469],
       [ 2920,   780]], dtype=int64)

In [43]:
from sklearn.metrics import classification_report

In [44]:
print(classification_report(Ytest,y_pred))

              precision    recall  f1-score   support

       <=50K       0.79      0.96      0.87     11360
        >50K       0.62      0.21      0.32      3700

    accuracy                           0.77     15060
   macro avg       0.71      0.58      0.59     15060
weighted avg       0.75      0.77      0.73     15060

In [45]:
salary_GB = GB()

In [46]:
salary_GB.fit(Xtrain,Ytrain)

GaussianNB()

In [47]:
y_pred = salary_GB.predict(Xtest)

In [48]:
acc = accuracy_score(Ytest, y_pred) * 100
print("Accuracy =", acc)

Accuracy = 79.15006640106242

In [49]:
confusion_matrix(Ytest, y_pred)

array([[10784,   576],
       [ 2564,  1136]], dtype=int64)

In [50]:
print(classification_report(Ytest,y_pred))

              precision    recall  f1-score   support

       <=50K       0.81      0.95      0.87     11360
        >50K       0.66      0.31      0.42      3700

    accuracy                           0.79     15060
   macro avg       0.74      0.63      0.65     15060
weighted avg       0.77      0.79      0.76     15060